services:
  - type: web
    name: mocksy-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./startup.sh
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: ALGORITHM
        value: HS256
      - key: GROQ_ENABLED
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mocksy-db
          property: connectionString

databases:
  - name: mocksy-db
    databaseName: mocksy_db
    user: mocksy_user
    plan: free
