"""add designation column

Revision ID: 10d17d4eba71
Revises: 
Create Date: 2026-04-08 18:14:39.989141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10d17d4eba71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    # op.drop_table('users')
    # op.drop_table('interviews')
    # op.drop_table('cvs')
    # op.drop_table('questions')
    # op.drop_table('answers')
    # # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('users', 'designation')